version: '3.9'

services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - valkey-data:/data
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: askell
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  valkey-data:
  postgres-data:
